apiVersion: v1
kind: Service
metadata:
        name: clientsvc
        labels:
                app: client
spec:
        type: NodePort
        selector:
                app: client
        ports:
                - name: http
                  port: 8888
                  targetPort: 8888
                  nodePort: 30303
