apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: virgin


#eksctl create cluster -f eksconf.yml
#eksctl get nodegroup --cluster EKS-course-cluster
#kubectl get nodes


  # - name: ng-mixed
  #   minSize: 2
  #   maxSize: 4    
  #   instanceDistribution:
  #     maxPrice: 0.2
  #     instanceTypes: ["t2.small", "t3.small"]
  #     onDemandBaseCapacity: 0
  #     onDemandPercentageAboveBaseCapacity: 50
  #   ssh:
  #     publicKeyName: virgin
#eksctl create nodegroup --config-file=eksconf.yml --include='ng-mixed'
#eksctl delete nodegroup --config-file=eksconf.yml --include='ng-mixed' --approve