apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clientpod.fullname" . }}
  labels:
    {{- include "clientpod.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clientpod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clientpod.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{.Values.env.name}}
              value: {{.Values.env.value}}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP