apiVersion: v1
kind: Service
metadata:
        name: serversvc
spec:
        type: ClusterIP
        selector:
                app: server
        ports:
                - name: http
                  port: 8989
                  targetPort: 8989
        
